version: "2"
linters:
  enable:
    - asciicheck
    - dupl
    - gocyclo
    - gosec
    - misspell
    - revive
    - whitespace
  settings:
    revive:
      rules:
        - name: var-naming
          arguments:
            - - ID
              - URL
              - JSON
              - URI
            - - ""
          severity: warning
          disabled: false
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - revive
        text: ALL_CAPS
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
