MD013:
  # Number of characters
  line_length: 110
  # Number of characters for headings
  heading_line_length: 110
  # Number of characters for code blocks
  code_block_line_length: 145
  # Include code blocks
  code_blocks: true
  # Include tables
  tables: true
  # Include headings
  headings: true
  # Strict length checking
  strict: false
  # Stern length checking
  stern: false
